dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2
  - Brechtpd/base64@1.1.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2'
      - '@brechtpd=Brechtpd/base64@1.1.0'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
